import React from "react";
import Head from "next/head";
import { About, FlyCoffee, Footer, Header} from "components";
const AboutUs = () => {
  return <>
    <Head>
        <title>Coffee CupZ | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <About />
    <FlyCoffee />
    <Footer />

  </>
};

export default AboutUs;
