import React from "react";
import Head from "next/head";
import { FlyCoffee, Footer, Header, Team } from "components";
const AboutTeam = () => {
  return (
    <>
      <Head>
        <title>Coffee CupZ | Our Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Team />
      <FlyCoffee />
      <Footer />
    </>
  );
};

export default AboutTeam;
