import React from "react";
import Head from "next/head";
import { FlyCoffee, Footer, Header, OurGallery } from "components";

const Gallery = () => {
  return (
    <>
      <Head>
        <title>Coffee CupZ | Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <OurGallery />
      <FlyCoffee />
      <Footer />
    </>
  );
};

export default Gallery;
