import { Banner, FlyCoffee, Footer, Header, HomeAbout, Roadmap } from "components";
import Head from "next/head";
import { AnimationOnScroll } from 'react-animation-on-scroll';
export default function Home() {
  return (
    <>
      <Head>
        <title>Coffee CupZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Header />
      <Banner />
    
        <HomeAbout />

      <Roadmap />
      <FlyCoffee />
      <Footer />
    </>
  );
}
